# Generated by Django 4.2.3 on 2023-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=259, verbose_name='заголовок')),
                ('description', models.TextField(max_length=999, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('auction', models.BooleanField(help_text='Тыкай если торговец!', verbose_name='поторгуемся?')),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
