# Generated by Django 4.2.3 on 2023-07-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0002_advertisement_created_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='created_update',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
