# Generated by Django 4.2.3 on 2023-07-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0003_remove_advertisement_created_update_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
