# Generated by Django 4.2.3 on 2023-07-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0006_alter_advertisement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявления'},
        ),
    ]
